[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
basic-merkle-tree = { path = "../program" }
borsh = "1.5"
shellexpand = "3.1"
solana-client = "2.1"
solana-sdk = "2.1"
solana-transaction-status-client-types = "2.1"
