[package]
name = "basic-merkle-tree"
edition = "2021"

[dependencies]
borsh = "1.5"
solana-invoke = "0.2"
solana-program = "2.1"

[dev-dependencies]
solana-program-test = "2.1"
solana-sdk = "2.1"
tokio = "1"

[lib]
crate-type = ["cdylib", "lib"]
